# Cloud Code Configuration
# Este arquivo configura o Cloud Code para deployment direto do VS Code

# Deploy Instructions:
# 1. Abra Command Palette (Ctrl+Shift+P)
# 2. Digite "Cloud Code: Deploy to Cloud Run"
# 3. Siga as instruções do assistente

# Local Development:
# 1. Command Palette → "Cloud Code: Run on Cloud Run Emulator"
# 2. Isso executará sua aplicação localmente simulando Cloud Run

# Debugging:
# 1. Command Palette → "Cloud Code: Debug on Cloud Run Emulator"
# 2. Permite debugging local com breakpoints

project_settings:
  default_region: "us-central1"
  default_service_name: "veracare-podologia"
  
cloud_run:
  # Configurações específicas para Cloud Run
  cpu: "1"
  memory: "512Mi"
  concurrency: 80
  min_instances: 0
  max_instances: 10
  
  # Variáveis de ambiente para produção
  env_vars:
    NODE_ENV: "production"
    PORT: "8080"
    
  # Configurações de tráfego
  traffic:
    - percent: 100
      latestRevision: true